const editorPicks = [
  {
    id: 1,
    img: "/images/food.jpg",
    tag: "Food",
    date: "11/22/2024",
    color: "#fde68a",
    title: "Magical Title For Food",
    author: "Susanna Paul"
  },
  {
    id: 2,
    img: "/images/coding.jpg",
    tag: "Coding",
    date: "02/11/2024",
    color: "#d9f99d",
    title: "Wonderful Coding Blog Title",
    author: "Stephen Smith"
  },
  {
    id: 3,
    img: "/images/travel.jpg",
    tag: "Travel",
    date: "01/04/2024",
    color: "#fed7aa",
    title: "Fun Travel Blog Title",
    author: "James Doe"
  },
  {
    id: 4,
    img: "/images/style.jpg",
    tag: "Style",
    date: "04/01/2024",
    color: "#fecaca",
    title: "Beautiful Posting About Style",
    author: "Jessica Ayres"
  },
  {
    id: 5,
    img: "/images/culture.jpg",
    tag: "Culture",
    date: "09/12/2024",
    color: "#bae6fd",
    title: "Important Title For Culture",
    author: "Thomas Grumley"
  },
  {
    id: 6,
    img: "/images/fashion.jpg",
    tag: "Fashion",
    date: "12/07/2024",
    color: "#ddd6fe",
    title: "Fashion Blog Title",
    author: "Julia Sam"
  }
];

const mainRecommended = [
  "Plant-Based Protein",
  "DIY Projects",
  "Travel Tips",
  "Meal Prep",
  "Design",
  "Future Of AI",
  "Historical",
  "Designer Shoes",
  "Software Engineering",
  "Interview Preparation",
  "Upcoming Trends",
  "Seasonal Ingredients",
  "Fast",
  "Comfort",
  "Historical",
  "Photography"
];

const category = [
  { value: 1, label: "style" },
  { value: 2, label: "fashion" },
  { value: 3, label: "coding" },
  { value: 4, label: "travel" },
  { value: 5, label: "food" },
  { value: 6, label: "culture" }
];

const tags = [
  { value: 1, label: "Plant-Based Protein" },
  { value: 2, label: "DIY Projects" },
  { value: 3, label: "Travel Tips" },
  { value: 4, label: "Meal Prep" },
  { value: 5, label: "Design" },
  { value: 6, label: "Future Of AI" },
  { value: 7, label: "Historical" },
  { value: 8, label: "Designer Shoes" },
  { value: 9, label: "Software Engineering" },
  { value: 10, label: "Interview Preparation" },
  { value: 11, label: "Upcoming Trends" },
  { value: 12, label: "Seasonal Ingredients" },
  { value: 13, label: "Healthy" },
  { value: 14, label: "Comfort" },
  { value: 15, label: "Vegetarian / Vegan" },
  { value: 16, label: "International" },
  { value: 17, label: "Baking / Pastry" },
  { value: 18, label: "Photography" },
  { value: 19, label: "Web Development" },
  { value: 20, label: "Mobile Development" },
  { value: 21, label: "Data Science" },
  { value: 22, label: "Artificial Intelligence" },
  { value: 23, label: "Game Development" },
  { value: 24, label: "Open Source Projects" },
  { value: 25, label: "Adventure" },
  { value: 26, label: "Cultural" },
  { value: 27, label: "Budget" },
  { value: 28, label: "Solo" },
  { value: 29, label: "Ecotourism" },
  { value: 30, label: "Casual" },
  { value: 31, label: "Formal" },
  { value: 32, label: "Street" },
  { value: 33, label: "Vintage" },
  { value: 34, label: "Bohemian" },
  { value: 35, label: "Athletic" },
  { value: 36, label: "Art" },
  { value: 37, label: "Literature" },
  { value: 38, label: "Music" },
  { value: 39, label: "Tradition" },
  { value: 40, label: "Festivals" },
  { value: 41, label: "Language & Linguistics" },
  { value: 42, label: "High" },
  { value: 43, label: "Sustainable" },
  { value: 44, label: "Fast" },
  { value: 46, label: "Luxury" },
  { value: 47, label: "DIY" },
  { value: 48, label: "Shows" },
  { value: 49, label: "Runway" },
  { value: 50, label: "Thrift" },
  { value: 51, label: "Second-Hand" },
  { value: 52, label: "Trendy" },
  { value: 53, label: "Royalty" },
  { value: 54, label: "Avant Garde" },
  { value: 55, label: "Diversity" },
  { value: 56, label: "Pop Culture" },
  { value: 57, label: "Sociology" },
  { value: 58, label: "Globalization" },
  { value: 59, label: "Multiculturalism" },
  { value: 60, label: "Self-Care" },
  { value: 61, label: "Minimalism" },
  { value: 62, label: "Distributed Systems" },
  { value: 63, label: "Operating Systems" },
  { value: 64, label: "IoT" },
  { value: 65, label: "Blockchain" },
  { value: 66, label: "Cryptocurrency" },
  { value: 67, label: "Multithreading" },
  { value: 68, label: "Linux" },
  { value: 69, label: "SQL" },
  { value: 70, label: "Exercise" },
  { value: 71, label: "Organic" },
  { value: 72, label: "Snacks" },
  { value: 73, label: "Dessert" },
  { value: 74, label: "Farm" },
  { value: 75, label: "Farmers Market" },
  { value: 76, label: "International Destinations" },
  { value: 77, label: "Railway Travel" },
  { value: 78, label: "Aerospace" },
  { value: 79, label: "Accommodations" },
  { value: 80, label: "Transportation" },
  { value: 81, label: "Luggage" },
  { value: 82, label: "Passport" },
  { value: 83, label: "Urban" },
  { value: 84, label: "Pop" },
  { value: 85, label: "Idealism" },
  { value: 86, label: "Folk" },
  { value: 87, label: "Community" },
  { value: 88, label: "Values" },
  { value: 89, label: "Indie" },
  { value: 90, label: "Trans-Racial" },
  { value: 91, label: "Preppy" },
  { value: 92, label: "Artsy" },
  { value: 93, label: "Gothic" },
  { value: 94, label: "Ethnic" },
  { value: 95, label: "Elegant" },
  { value: 96, label: "Chic" },
  { value: 97, label: "Grunge" },
  { value: 98, label: "Minimalist" }
];

export default {
  editorPicks,
  mainRecommended,
  tags,
  category
};
